project:
  type: website
  output-dir: docs

website:
  title: "ALADYM Tuning tutorial"
  search: false
  navbar:
    title: false
    logo: COISPA_colour.png
    left:
      - href: ALADYM_tuning_tutorial.qmd
    right:
      - text: "Fondazione COISPA Website"
        href: https://www.fondazionecoispa.org/
      - text: "COISPA Github"
        href: https://github.com/COISPA

format:
  html:
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: true
    toc-title: "Index"
    number-sections: false
    df-print: paged
    include-in-header: icons.html
    theme: default
    smooth-scroll: true
    css: styles-quarto.css

execute:
  warning: false
  message: false
